console.log("Azie Melza Pratama")
console.log(18)
console.log("Jl.Ekamai No.50, Kel.Sukadana, Kec.Kayuagung, Kab.OKI, Sumatera Selatan")
console.log("Programming, Heavy-Lifting")
console.log("Universitas Sriwijaya, Teknik Informatika")
console.log("Programming sangat menarik karena kita bisa mengendalikan mesin sesuai perintah kita, banyak sekali kreatifitas yg bisa dikembangkan dengan kemampuan itu")
console.log("Java, HTML, CSS, Javascript, NodeJS")
console.log("Belajar programming sangatlah menyenangkan, baru pertama kali saya dalam seumur hidup belajar sesuatu namun saya tidak merasa jenuh dengan cepat, hal yang kadang sulit dihadapi adalah ketika kita mengetahui programming bukan hanya sekedar mengetikkan kode di komputer saja, namun banyak sekali teknologi yang terlibat, seperti cloud computing, API, Microservices Architecture, dll. Sehingga membuat kita bingung ingin mempelajari yg mana dulu")
console.log("Karena saya ingin meningkatkan kemampuan Web-Development saya dengan mengikuti program yg dijalankan FAZZTRACK")
console.log("Saya memiliki kemauan dan kemampuan belajar, serta Stress-tolerance yang tinggi. Selama liburan semester ini saya selalu menempa kemampuan programming saya, karena programming sangatlah menyenangkan bagi saya sehingga saya tidak pernah merasa jenuh dalam mempelajarinya. Maka daripada itu, FAZZTRACK bisa memberi saya kesempatan untuk menempah dan mengembangkan passion saya lebih jauh")